# Generated by Django 4.0.5 on 2022-06-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyDetails',
            new_name='Company',
        ),
    ]
